playersSpawn:
  green:
    type1:
      x: 7
      y: 52
      z: 1
    type2:
      x: 7
      y: 52
      z: 3
    type3:
      x: 7
      y: 52
      z: -0
  red:
    type1:
      x: -12
      y: 52
      z: 3
    type2:
      x: -12
      y: 52
      z: 3
    type3:
      x: -12
      y: 52
      z: 3