name: pluginTest
version: '${project.version}'
main: com.yorkys.plugintest.Main
commands:
  gmc:
    description: Switch between gmc and gms
    usage: /gmc
  mg:
    description: MiniGame commands
    usage: /mg